### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by unixfox** [ibv/LDAP-Admin#1]
I don't find any binary inside the repo or in release section and I never compiled pascal so I don't know how to compile LDAP-Admin?

**Comment by ibv** [comment]
Yes, there are only source code.
The procedure for compilation:
   -  install Lazarus (1.6 or above) from binaries - http://wiki.freepascal.org/Installing_Lazarus
   -  get source code Ldap-Admin from  https://github.com/ibv/LDAP-Admin 
   -  in Lazarus IDE, menu -  File -> Open ->  "/path/to/LdapAdmin.lpi" 
   -  in Lazarus IDE,  menu - Run -> F9 (run) or Ctrl+F9 (compile) or Shift+F9 (link)
