### ISSUE TITLE
Compiled Binary 

### ISSUE THREAD

**Issue by kp2401075** [ibv/LDAP-Admin#10]
Hi,

I was wondering if you could have compiled binary on the release.

so that users don't have to install Lazarus and compile.

Kind Regards

**Comment by ibv** [comment]
Hi,

at the release site is adding a binary code,
tested on Mageia 5, CentOS 7.5

![ld-1](https://user-images.githubusercontent.com/2648561/59751491-e790b380-9280-11e9-96a5-0c75b964fab9.png)

**Comment by kp2401075** [comment]
Thank you very much.
 This will be very helpful for many users
