### ISSUE TITLE
Reusing the program has saved the host disappears

### ISSUE THREAD

**Issue by qizai123** [ibv/LDAP-Admin#11]
Very good design allows me to migrate to Linux office seamlessly, but I don't know why every time I re-open the program, my saved host is disappears.   I work at Deepin 15.11, which is a very good desktop Linux system.

**Comment by ibv** [comment]
Hello,
can you try this procedure in  https://github.com/ibv/LDAP-Admin/issues/6 ?

**Comment by qizai123** [comment]
Thank you very much, #6 helped me solve the problem.
