### ISSUE TITLE
the interface need optimize

### ISSUE THREAD

**Issue by widon1104** [ibv/LDAP-Admin#13]
![截图_选择区域_20220612134118](https://user-images.githubusercontent.com/12093211/173217453-18ce809a-1ee6-40a5-ac54-a62e0681f195.jpg)

the interface of ldap-admin for linux looks strange need optimize.
I use uos21.3(linux distribution based on debian).

**Comment by ibv** [comment]
Hi,
I'll try to do something about it, but on my home PC (Mageia 8, plasma) the interface is correct.
![o-44](https://user-images.githubusercontent.com/2648561/173325678-2d0c39ca-f19d-4907-8fe9-8b625f8c230a.png)

xdpyinfo | grep -B 2 resolution
![o-45](https://user-images.githubusercontent.com/2648561/173325770-fa3394a7-51e1-4f63-9912-d7aaaa515839.png)

**Comment by widon1104** [comment]
➜  ~ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    2560x1440 pixels (675x379 millimeters)
  resolution:    96x97 dots per inch

**Comment by ibv** [comment]
Please try version 1.8.3.10, in release section.
I don't have a monitor with such a resolution.

**Comment by widon1104** [comment]
![image](https://user-images.githubusercontent.com/12093211/174434661-288370e9-f0c3-41ee-b77f-980e9b2791de.png)
I use 1.8.3.10，the interface status has improved.

**Comment by ibv** [comment]
Fixed scaled DPI in commit https://github.com/ibv/LDAP-Admin/commit/1ea8e83dd3101e4476bcfdee78710138f5ff5c42
