### ISSUE TITLE
LdapAdmin version 1.8.3.10 does not save configurations

### ISSUE THREAD

**Issue by giannibassiniprovincia** [ibv/LDAP-Admin#17]
Hi
I put Ldapadmin executable in my home dir but it doesn't save the configured servers connections when I exit from the Ldapadmin with the red button.

**Comment by ibv** [comment]
Hi,
please try the procedure described here [#6](https://github.com/ibv/LDAP-Admin/issues/6)

**Comment by giannibassiniprovincia** [comment]
solved thanks
