### ISSUE TITLE
build on 32bit

### ISSUE THREAD

**Issue by blackPantherOS** [ibv/LDAP-Admin#2]
Hi, I tried build on 32bit linux system..
```
....
200 93.530/97.952 Kb Used
/...../BUILD/LDAP-Admin-1.8.0/Config.pas(243,43) Error: (3236) Generics without specialization cannot be used as a type for a variable
/...../BUILD/LDAP-Admin-1.8.0/Config.pas(243,43) Fatal: (2003) Syntax error, ";" expected but "<" found
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppc386 returned an error exitcode ( normal if you did not specify a source file to be compiled)
Error: (lazarus) Projekt fordítása, Cél: LdapAdmin: stopped with exit code 1
ERROR: failed compiling of project /..../BUILD/LDAP-Admin-1.8.0/LdapAdmin.lpi

```
You have any idea?
Thx

**Comment by ibv** [comment]
Which of versions Lazarus and FPC?

**Comment by blackPantherOS** [comment]
fpc -v
Free Pascal Compiler version 2.6.4 [2016/06/14] for i386
Copyright (c) 1993-2014 by Florian Klaempfl and others
lazbuild -v
1.6

**Comment by ibv** [comment]
Try it update fpc to version 3.0.0 and Lazarus to 1.6.2 (but not 1.6.4 !)

![laz-1](https://cloud.githubusercontent.com/assets/2648561/26551433/d149bfde-4482-11e7-95d5-8a560465dc37.png)

**Comment by blackPantherOS** [comment]
Okay, thx, I will try

**Comment by blackPantherOS** [comment]
Hi, build complete with fpc-3.0 and lazarus 1.6.2 and 1.6.4 as well.. We will adding initial RPM package to blackPanther OS devel repo today.
Thank you 

![ldapadmin](https://cloud.githubusercontent.com/assets/12883566/26730609/cd77d79c-47b1-11e7-95ee-026fc8f7a71b.jpg)
