### ISSUE TITLE
Connections not displayed in list or table format

### ISSUE THREAD

**Issue by rabid-user** [ibv/LDAP-Admin#4]
I have a set of connections defined which display correctly in either small or large icon format. 

If I change the format to list or table, the entries seem to exist since the scrollbar appears to be the right size for the number of entries and they can be selected, but the icons and names aren't actually visible/displayed.

What information do you need to investigate?

**Comment by ibv** [comment]
Yes its bug, fixed in commit afacda1,
you must delete files ConnList.o, ConnList.ppu and ConnList.dfm in directory ppu, 
get last version LDAP-Admin (ConnList.dfm) from GitHub and compile new version

**Comment by rabid-user** [comment]
All good now - much appreciated!!!
