### ISSUE TITLE
should only be name in connection list

### ISSUE THREAD

**Issue by rabid-user** [ibv/LDAP-Admin#5]
I should have noticed this earlier when you fixed the list and table options. 

In the table option, there are multiple columns with a header row. In the list option, there is no header row,but for some reason there are still columns. 

The list option should only show the connection name.

**Comment by ibv** [comment]
Yes it is a problem, I think it's standard TListView behavior in Lazarus,
in Delphi, the component behaves as you write,
I do not have a simple way to repair
