### ISSUE TITLE
Unable to remove uniqueMember attr from GroupOfUniqueNames group

### ISSUE THREAD

**Issue by wodz** [ibv/LDAP-Admin#8]
Windows version 1.8.3.0 works as expected, linux version compiled from 16d009dbd859d493cc28f31af4fa42bf704cf0b3 refuses to do so. The backtrace of failing operation:
TApplication.HandleException LDAP error: No such attribute!
  Stack trace:
  $0000000000479ACA line 685 of LDAPClasses.pas
  $000000000047AD9D line 1090 of LDAPClasses.pas
  $000000000047AC2A line 1115 of LDAPClasses.pas
  $000000000047F205 line 2224 of LDAPClasses.pas
  $00000000004A1AA0 line 374 of Group.pas
  $00000000004A189A line 353 of Group.pas
  $000000000044F38A line 959 of include/customform.inc
  $000000000044CE93 line 34 of include/customform.inc
  $0000000000454C22 line 3011 of include/customform.inc
  $00000000004FE572 line 518 of Connection.pas
  $000000000046B589 line 1920 of Main.pas
  $000000000046B622 line 1928 of Main.pas
  $00000000004682CF line 1285 of Main.pas
  $00000000005FCB76 line 1658 of include/control.inc
  $00000000005FE94D line 2511 of include/control.inc
  $0000000000430DEF
  $00000000005F093D line 5397 of include/wincontrol.inc

It is TLDAPSession.WriteEntry(Entry: TLdapEntry) which fails and it is significantly different between windows and linux.

OpenLDAP server log has such error:
conn=1020 op=19 MOD dn="cn=testgroup,ou=Groups,dc=example,dc=com"
conn=1020 op=19 MOD attr=uniqueMember
conn=1020 op=19 RESULT tag=103 err=16 text=modify/delete: uniqueMember: no such value

So it looks like uniqueMember value to be deleted is wrong. GroupOfUniqueNames.RemoveMember() is called with correct value string.

**Comment by ibv** [comment]
Fixed in commit fe1058d
