### ISSUE TITLE
jpegPhoto attribute support is broken

### ISSUE THREAD

**Issue by wodz** [ibv/LDAP-Admin#9]
The bug is twofold:
1) Inserting jpeg image from LDAP admin inserts incorrect data (truncated and mangled). First kB or so is correct, the rest is garbage.
2) Correctly inserted image (by JXplorer, but also validated this using ldap3 python module) is not displayed in Personal tab and LDAP admin throws exception:
 TApplication.HandleException JPEG error
  Stack trace:
  $0000000000772965
  $0000000000778C82
  $00000000006455E9 line 141 of include/fpimagebitmap.inc
  $000000000062FB74 line 441 of include/rasterimage.inc
  $000000000062FA48 line 417 of include/rasterimage.inc
  $00000000004BD48E line 877 of Misc.pas
  $00000000004C5056 line 142 of InetOrg.pas
  $0000000000474354 line 875 of User.pas
  $0000000000666B26 line 334 of include/customnotebook.inc
  $000000000066861D line 1051 of include/customnotebook.inc
  $00000000006687B0 line 1101 of include/customnotebook.inc
  $0000000000430DEF
  $00000000005F085D line 5397 of include/wincontrol.inc
  $00000000005DE091 line 3257 of controls.pp
  $00000000005F4945 line 7260 of include/wincontrol.inc
  $0000000000430DEF
  $00000000005F085D line 5397 of include/wincontrol.inc

**Comment by ibv** [comment]
Fixed in commit aea488b
